namespace: nokia
name: sros
version: 1.6.0
readme: README.md
authors:
- Sven Wisotzky <sven.wisotzky@nokia.com>
description: Ansible collection to support networking devices running Nokia SR OS
license: BSD-3-Clause
requires_ansible: ">=2.13"
tags:
- collection
- network
- networking
- backup
- mpls
- nokia
- sros
- timos
- netconf
- cli
- cliconf
- terminal
- ansible

repository: https://github.com/nokia/ansible-networking-collections/tree/HEAD/sros
documentation: https://github.com/nokia/ansible-networking-collections/tree/HEAD/sros
homepage: https://github.com/nokia/ansible-networking-collections/tree/HEAD/sros
issues: http://github.com/nokia/ansible-networking-collections/issues
